- type: replace
  path: /instance_groups/name=api/jobs/-
  value:
    name: cf-admin-user
    release: collection-of-pullrequests
    properties:
      api_url: "https://api.((system_domain))"
      ca_cert: "((router_ssl.certificate))"
      admin_username: admin
      admin_password: "((cf_admin_password))"

- type: replace
  path: /releases/-
  value:
    name: collection-of-pullrequests
    version: latest
