---
name: pre-start-script

instance_groups:
- name: pre-start-script
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: pre-start-script
    release: collection-of-pullrequests
    properties:
      script: |-
          #!/bin/bash

          cat > /etc/profile.d/git-aliases.sh <<EOF
          alias gl="git pull"
          EOF

          apt-get update
          apt-get install wget git tmux -y
          wget -q -O - https://raw.githubusercontent.com/starkandwayne/homebrew-cf/master/public.key | apt-key add -
          echo "deb http://apt.starkandwayne.com stable main" | tee /etc/apt/sources.list.d/starkandwayne.list
          apt-get update
          apt-get install bosh-cli


variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: collection-of-pullrequests
  version: 1.1.0
  url: https://github.com/cloudfoundry-community/collection-of-pullrequests-boshrelease/releases/download/v1.1.0/collection-of-pullrequests-1.1.0.tgz
  sha1: 8cd9950a3d7c2f51a363a1ce41b930e6851611aa
