---
name: prepare-env

instance_groups:
- name: prepare-env
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: prepare_env
    release: collection-of-pullrequests
    properties:
      script: |-
          #!/bin/bash

          cat > /etc/profile.d/git-aliases.sh <<EOF
          alias gl="git pull"
          EOF

          apt-get update
          apt-get install wget git tmux -y
          wget -q -O - https://raw.githubusercontent.com/starkandwayne/homebrew-cf/master/public.key | apt-key add -
          echo "deb http://apt.starkandwayne.com stable main" | tee /etc/apt/sources.list.d/starkandwayne.list
          apt-get update
          apt-get install bosh-cli


variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: collection-of-pullrequests
  version: latest # TODO: update after first final release
  # url:            TODO: update after first final release
  # sha1:           TODO: update after first final release
